version: "3"
services:
    nginx-book-note:
        image: nginx:1.20
        ports:
            - 9090:80
        volumes:
            - $PWD/build/html:/usr/share/nginx/html
        restart: always
